### ISSUE TITLE
GitHub stats row is wrapping on some cards

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#15]
See the two cards on the left side of this screenshot:

![image](https://user-images.githubusercontent.com/54865/39411242-32088f68-4bbb-11e8-9d6f-20823daa9f7b.png)

**Comment by maoo** [comment]
Couldn't reproduce it. @pmonks - is this still happening now? Maybe the CSS width have been fixed already.

**Comment by pmonks** [comment]
Yes:

![image](https://user-images.githubusercontent.com/54865/39830141-623fc7d4-5375-11e8-9b31-918114c3f90a.png)

Note that it only appears to happen on cards where the fork / watcher / star / contributor counts are high (multi-digit numbers).

**Comment by maoo** [comment]
Sorry, cannot reproduce this issue. Can you please HTML inspect the element and check if raising the CSS `width` of a card fixes the issue? See https://github.com/finos/finos.github.io/blob/master/css/catalogue.css#L140

**Comment by maoo** [comment]
May be related with the scrolling (on the right card, not shown on the left one); can you try now on http://rawgit.com/finos/finos.github.io/staging/index.html ?

**Comment by pmonks** [comment]
The issue is fixed there, but it's created a worse problem - the cards take up too much horizontal space:

![image](https://user-images.githubusercontent.com/54865/39948808-816832aa-552c-11e8-92c8-76d263ecb34f.png)
