### ISSUE TITLE
Lifecycle state badges should be hyperlinked to associated state wiki pages

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#25]
For example:

[![FINOS Operating](https://cdn.rawgit.com/finos/contrib-toolbox/master/images/badge-operating.svg)](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/93061261/Operating)

i.e. ![FINOS Operating](https://cdn.rawgit.com/finos/contrib-toolbox/master/images/badge-operating.svg) is hyperlinked to [https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/93061261/Operating](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/93061261/Operating)

Each of the lifecycle state pages are children of [this page](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530756/Project+and+Working+Group+Lifecycles).

**Comment by maoo** [comment]
Fixed on https://rawgit.com/finos/finos.github.io/staging/index.html
