### ISSUE TITLE
With new programs added, program filter is messed up

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#27]
As seen here:
![image](https://user-images.githubusercontent.com/54865/39900388-636c99be-5476-11e8-93a7-9bc1f9d65609.png)

**Comment by maoo** [comment]
Can you please provide a JSON file so I can reproduce the issue?

**Comment by maoo** [comment]
nvmd, found it on master.

Would be great to push activities.json to staging too and avoid the 2 branches to be out of sync
