### ISSUE TITLE
Provide hover text for language icons

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#34]
The language icons are not necessarily self explanatory to folks who aren't familiar with the chosen iconography of the given language community.

For example:
![image](https://user-images.githubusercontent.com/54865/39941453-750e1c88-5511-11e8-91f0-f06e31ca58b8.png)
![image](https://user-images.githubusercontent.com/54865/39941462-7b2505c8-5511-11e8-84fb-a0a55f82c1e4.png)

To address this, all language icons should have a mouseover popup containing the human-readable name of the language.  This might, for example, be provided using the HTML `<img>` tag's `title` attribute (which will display a small popup when the image is moused over).

**Comment by maoo** [comment]
Fixed now on http://rawgit.com/finos/finos.github.io/staging/index.html

**Comment by pmonks** [comment]
The language names in these mouseover popups need to match the language names used in the filter control (i.e. they need to be human readable).  Here's an example of where that's not the case:

![screen shot 2018-05-11 at 3 13 04 pm](https://user-images.githubusercontent.com/54865/39949172-09fb4124-552e-11e8-9eeb-96657975ef07.png)

**Comment by maoo** [comment]
Fixed on https://rawgit.com/finos/finos.github.io/staging/index.html ; also added the # of lines in the alt, thought it would be useful.
