### ISSUE TITLE
Regression: some language filters no longer work

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#38]
It appears the fix for issue #24 broke filtering for some languages:

![image](https://user-images.githubusercontent.com/54865/39948994-4c5ad652-552d-11e8-84ca-e02cb1beb251.png)

**Comment by maoo** [comment]
Tested on https://rawgit.com/finos/finos.github.io/staging/index.html with values `C#, C++, Objective C, Objective C++`; values look fine in the filters and images alt texts.
