### ISSUE TITLE
Sorting by heat is not working properly

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#7]
Note that this might be a data problem in the `activities.json` file, rather than a problem in the code.  That hasn't been triaged yet.

**Comment by maoo** [comment]
Seems to work fine now; all activities without `heat` are always listed at the bottom of the results; not sure if this is the expected behaviour; if not, feel free to reopen the issue.

**Comment by pmonks** [comment]
That's not correct, no.  Activities without a "heat" property should be considered to have a heat of zero (0), meaning that when activities are sorted by heat ascending, they should appear at the top.

**Comment by maoo** [comment]
Done; can you please review now?

**Comment by pmonks** [comment]
👍 LGTM!  👍
